# Generated by Django 4.2.1 on 2023-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='view_count',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='averageRateCount',
            new_name='average_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='fiveStar',
            new_name='five_star',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='fourStar',
            new_name='four_star',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='oneStar',
            new_name='one_star',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='threeStar',
            new_name='three_star',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='totalRateCount',
            new_name='total_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='twoStar',
            new_name='total_rate_count',
        ),
        migrations.AddField(
            model_name='rate',
            name='two_star',
            field=models.IntegerField(default=0),
        ),
    ]
