# Generated by Django 4.2.1 on 2023-05-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_review_product_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
    ]
