# Generated by Django 4.2.1 on 2023-05-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ecommerce.product'),
        ),
    ]
